# only run for: merge commits, releases and pull-requests
if: type != push OR branch = master OR branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  include:
    - &macOS
      os: osx
      osx_image: xcode10.1
      name: macOS / Swift 4.2.1
      script: brew install ./swift-sh.rb
      env:
        - HOMEBREW_NO_AUTO_UPDATE=1
        - HOMEBREW_NO_INSTALL_CLEANUP=1

    - <<: *macOS
      name: macOS / Swift 5.0.x
      osx_image: xcode10.2

    - <<: *macOS
      name: macOS / Swift 5.1.x
      osx_image: xcode11

    - <<: *macOS
      name: macOS / Swift 5.0.x / --force-bottle
      osx_image: xcode10.2
      script: |
        echo fail > $(brew --cache --build-from-source ./swift-sh.rb)
        # ^^ because the install will still *try* to build from source, so if that happens this will fail that attempt
        brew install ./swift-sh.rb --force-bottle

    - &linux
      name: Linux / Swift 4.2.4
      os: linux
      env: SWIFT_VERSION=4.2.4
      before_install: |
        curl "https://swift.org/builds/swift-$SWIFT_VERSION-release/ubuntu1604/swift-$SWIFT_VERSION-RELEASE/swift-$SWIFT_VERSION-RELEASE-ubuntu16.04.tar.gz" | sudo tar xz -C / --strip-components=1
        sudo chmod a+r /usr/lib/swift/CoreFoundation/*
      install: |
        sudo apt-get install clang libicu-dev
      before_script: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      script: |
        /home/linuxbrew/.linuxbrew/bin/brew install ./swift-sh.rb --verbose

    - <<: *linux
      name: Linux / Swift 5.0.0
      env: SWIFT_VERSION=5.0
      