# only run for: merge commits, releases and pull-requests
if: type != push OR branch = master OR branch =~ /^\d+\.\d+(\.\d+)?(-\S*)?$/

jobs:
  include:
    - &macOS
      os: osx
      osx_image: xcode10.1
      script: brew install ./swift-sh.rb

    - <<: *macOS
      osx_image: xcode10.2

    - os: linux
      before_install: |
        curl "https://swift.org/builds/swift-4.2.2-release/ubuntu1404/swift-4.2.2-RELEASE/swift-4.2.2-RELEASE-ubuntu14.04.tar.gz" | sudo tar xz -C / --strip-components=1
      install: |
        sudo apt-get install clang libicu-dev
      before_script: |
        sh -c "$(curl -fsSL https://raw.githubusercontent.com/Linuxbrew/install/master/install.sh)"
      script: |
        /home/linuxbrew/.linuxbrew/bin/brew install ./swift-sh.rb --verbose
